[webservers]
# Replace this IP with your actual AWS EC2 instance public IP address
100.53.138.0 ansible_user=ec2-user ansible_connection=ssh

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
